### ISSUE TITLE
Actionbar button size

### ISSUE THREAD

**Issue by themadtux** [tukui-org/Tukui#131]
![image](https://github.com/tukui-org/Tukui/assets/663501/742cb6ea-626c-4243-85b1-9864ce5a1284)
Having an issue with left/right buttons in the frame being smaller than they should be... is there a fix?

**Comment by tetuti** [comment]
This may be caused by an underlying "base UI". Try turning off Tukui (as well as other relevant addons) and go into edit mode. Are the "base" bars scaled? Reverting the scale of the base bars in the currently loaded "base UI" fixed this issue for me in earlier versions of Tukui.

The core issue is probably due to Tukui respecting the action bar scaling of the core UI rather than establishing a baseline of it's own. However I'm not well-versed in addon development so this is pure speculation.

**Tukui looking as "intended" with a base UI action bar button scale of 100%**

![tukui_100_percent_base_scale](https://github.com/tukui-org/Tukui/assets/5671933/6a35c8ab-3064-45aa-89de-5fb8882f81ac)
![base_ui_100_percent_scale_edit_mode](https://github.com/tukui-org/Tukui/assets/5671933/ee1cb5d1-b2fb-447d-8fbf-8a6517f5c806)

**Tukui with a base UI action bar button scale of 50%**

![tukui_50_percent_base_scale](https://github.com/tukui-org/Tukui/assets/5671933/6e16680e-dfa3-4f15-a401-bb5562120058)
![base_ui_50_percent_scale_edit_mode](https://github.com/tukui-org/Tukui/assets/5671933/5841543b-a518-4f3e-a73d-04c46dbc900f)
