### ISSUE TITLE
[BCC] Tooltip LUA Error after today's patch

### ISSUE THREAD

**Issue by UguMugu** [tukui-org/Tukui#16]
Don't know much about Addons, but I love this UI and after the most recent patch, this Error is shown almost instantly and keeps popping up.
![LUA Error1](https://user-images.githubusercontent.com/98029767/150135634-feadeb6c-a241-4d43-9269-45d94aa25e2f.JPG)

This is just the first part.

**Comment by Lethalix** [comment]
I believe this was fixed by https://github.com/tukui-org/Tukui/commit/8f6c3fcd54d45e44b58c21af7a25829bcdd8fdd7#diff-0f8b72555f7fd5d7954e155c035a4eb2b89d2a4bda7150fb93082b977c77539b

The change is available on git but it seems like the published version to tukui.org is still 20.24 (before the change). Personally, I applied the change locally to temporarily avoid the issue.

**Comment by Seppillado** [comment]
Hi, 

Apologies for my lack of understanding here, but how would I be able to apply such a fix, assuming that I have no working knowledge aside from how to install the add on? 

Is there a resource I could use to know how to patch these issues on my own such as the fix above locally?

**Comment by Lethalix** [comment]
To apply it manually in your `interface/addons/Tukui/Modules/Tooltips/Tooltips.lua` file change line 398 to be `if T.BCC and T.TocVersion < 20503 then`

Alternatively, you could download the addon from git, extract it, and dump it on top of your current installation of TukUI.
![image](https://user-images.githubusercontent.com/901436/150156996-06499606-6ce1-4d88-8b66-c6eaf4c7c924.png)

Keep in mind I'm not affiliated with TukUI, both of these should be viewed/as temporary workarounds until the officially published version has the fix.

**Comment by Seppillado** [comment]
Thank you so much!

**Comment by UguMugu** [comment]
Many thanks also from my side ^_^
