### ISSUE TITLE
[WotLK] Totem Bar keeps moving

### ISSUE THREAD

**Issue by t3hWheez** [tukui-org/Tukui#32]
Not sure what exactly is causing this but sometimes the Totem bar is moving down 100-150 pixels and to the left 100-150 pixels.  I wish I could give you more but I haven't found what exactly is causing it.

**Comment by psionikangel** [comment]
I am experiencing the same thing. I for one have identified some hints as to when it is happening.

1. It happens when in combat
2. It happens when I have my wolves out (so the pet bar appears).

Here is a screenshot of what it looks like
![shaman-multicast-bar-moving](https://user-images.githubusercontent.com/547413/192918548-c1da579d-5fd1-47be-b1dc-854db941dc5f.png)

**Comment by tukz** [comment]
I think this is fixed in latest release, 20.31, let's me know.

**Comment by t3hWheez** [comment]
Will check, I was worried to update with all the recent changes but will push the update tonight.

**Comment by t3hWheez** [comment]
Not resolved as of 20.31.

**Comment by tukz** [comment]
Worked on it for 2 hours, without any success, this bar is coded poorly by Blizzard and everytime I try to move it somewhere else, it taint the entire UI like crazy. So, disabled for 20.32 release, will try to restore it in a later build. Sorry.
